# Interactive brokers
ib_ipaddress: 127.0.0.1
ib_port: 7497
ib_idoffset: 100
broker_account: DU8511856

# MongoDB
mongo_host: mongodb://localhost:27017/
mongo_database_name: 'production'
mongo_port: 27017

# Parquet store
parquet_store: '/users/nicola/data/parquet'